-- Таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(200),
    login VARCHAR(200),
    user_name VARCHAR(200),
    birthday DATE
);

-- Таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    film_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50),
    description VARCHAR(200),
    release_date DATE,
    duration INTEGER,
    rating VARCHAR(10)
);

-- Таблица жанров
CREATE TABLE IF NOT EXISTS genres (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name VARCHAR(100)
);

-- Таблица лайков
CREATE TABLE IF NOT EXISTS likes (
    like_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER,
    user_id INTEGER,
    FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE
);

-- Таблица связей фильмов и жанров
CREATE TABLE IF NOT EXISTS film_genres (
    film_genres_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER,
    genre_id INTEGER,
    FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
    FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE
);

-- Таблица друзей пользователей
CREATE TABLE IF NOT EXISTS user_friends (
    user_friends_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    friend_user_id INTEGER,
    FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
    FOREIGN KEY (friend_user_id) REFERENCES users (user_id) ON DELETE CASCADE
);
